service: timelapse-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

custom:
  bucket: timelapse.ericjuli.us

functions:
  snapshot:
    handler: dist/handler.snapshot
    description:
    memorySize: 128
    events:
      - http:
          path: /snapshot
          method: get
      - http:
          path: /snapshot
          method: post
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
